package com.viadeo.kasper.gradle;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.Task;

class KasperIndexExtension {
    def String pigSourceDir = 'src/main/pig'
    def String hiveSourceDir = 'src/main/hive'
    def String avroSchemasDir = 'src/main/avro'
    def String avroSourceDir = 'generated-sources/avro'
    def String debianRootDir = 'usr/local/'
    def String debianDescription = 'Package generated by kasper-indexfor project '
}

class KasperIndex implements Plugin<Project> {
    void apply(Project project) {
        project.extensions.create("kasperIndexConf", KasperIndexExtension)
        project.kasperIndexConf.debianRootDir += project.name 
        project.kasperIndexConf.debianDescription += project.name

        //- Dependency to Kasper index packaging-------------------------------
        project.task(type: KasperIndexPackageTask, 'kasperIndexPackage')
        project.assemble.doLast {
            project.tasks.kasperIndexPackage.execute()
        }        

        //- Kasper index test dependencies ------------------------------------
        project.task(type: KasperIndexDependenciesTask, 'kasperIndexDependencies')
        project.check.doFirst {
            project.tasks.kasperIndexDependencies.execute()
        }

        //- Dependency to AVRO plugin -----------------------------------------
        project.apply plugin: 'avro-gradle-plugin'
        project.compileAvro {
            source = project.kasperIndexConf.avroSchemasDir
            destinationDir = project.file(project.kasperIndexConf.avroSourceDir)
        }
        project.sourceSets {
            main {
                java {
                    srcDir project.compileAvro.destinationDir
                }
            }
        }
        project.dependencies {
            project.compileAvro
        }

        //- Kasper index configurations ---------------------------------------
        project.configurations {
            pigRuntime {
                extendsFrom testRuntime
            }
            hiveRuntime {
                extendsFrom testRuntime
            }
        }

        //- Kasper index source sets ------------------------------------------
        project.sourceSets {
            main {
                resources {
                    srcDir project.kasperIndexConf.pigSourceDir
                    srcDir project.kasperIndexConf.hiveSourceDir
                }
            }
        }

        //- Dependency hacks --------------------------------------------------
        project.dependencies {
            compile("com.google.protobuf:protobuf-java:2.4.0a") {
                force = true
            }
        }

    }
}

