$script = <<SCRIPT
apt-get -y update
apt-get -y install wget node python-sphinx aptitude
apt-get -y install npm
npm install -g http://registry.npmjs.org/less/-/less-1.3.3.tgz
apt-get -y install inotify-tools
apt-get -y install make
apt-get install libgtk2.0-0

cd /tmp

if [ ! -f '/tmp/Sublime\ Text\ 2.0.2\ x64.tar.bz2' ]; then
    wget http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.2%20x64.tar.bz2
fi

tar xsfv '/tmp/Sublime\ Text\ 2.0.2\ x64.tar.bz2' -C /opt/.
mv '/opt/Sublime\ Text\ 2' /opt/sublime-text

cd /home/vagrant/doc
make html
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
  config.vm.synced_folder ".", "/home/vagrant/doc"
  config.vm.provision "shell", inline: $script
end
